### ISSUE TITLE
Check IPv6 support

### ISSUE THREAD

**Issue by adamansky** [wirow-io/wirow-server#11]
### Discussed in https://github.com/wirow-io/wirow-server/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **jjsarton** May 16, 2022</sup>
Actually wirow don't know about IPv6. </div>

**Comment by jjsarton** [comment]
./src/extern_ejdb2-build/src/extern_iwnet/src/ws/iwn_ws_server.c:
line 1945: shall be     .ai_family   = AF_UNSPEC,

The listening address decision taken within  gr.c shall problaby be ::1  and not 127.0.0.1

**Comment by adamansky** [comment]
Thank you a lot!

Fixed ai_family https://github.com/Softmotions/iwnet/commit/56ab0d0f6f9bc7d9b9c1f4228190a2179794bb54

> The listening address decision taken within gr.c shall problaby be ::1 and not 127.0.0.1

`gr.c`  is not touched, instead  you may specify IPv6 explicitly in config
```ini
[main]
ip = ::1
```

**Comment by jjsarton** [comment]
The changes within the config file don't change many thinks. I have also set <serverIPv6>@<serverIPv6> the results are always that mediasoup is called with a wrong ip string '' or '2001' (::1 ist wrong it shall be ::)

ERROR wrc.c:586: WRC<105666> Utils::IP::NormalizeIp() | throwing MediaSoupTypeError: invalid IP ''

**Comment by jjsarton** [comment]
Connectvity was tested:
The Wirow server (on a virtual cloud server)configured in order to announce both IPv4 and IPv6 (listen_announced_ips) , what listening on the address "::" (parameter ip).
One computer configured for IPv6 only, the other for IPv4 only.
Starting a meeting (first computer) and joining the meeting with the second computer worked perfectly.
I have modified the file src/gr.c in order to avoid stripping of the last part of the ip address. The block starting at line 185
```
for (i = i > j ? i - 1 : len - 2; i > j; --i) {
    if (server[i] == ':' && server[i + 1] > '0' && server[i + 1] <= '9') {
      k = i;
      break;
    }
 }
```
shall not be performed if type is GRSTART_FLAG_CONFIG_HAS_ANNOUNCED_IP

**Comment by adamansky** [comment]
Thank you for the hint! 63071fb should fix that. Please reopen on problems
